# Base image
FROM node:20-alpine

# Working directory inside container
WORKDIR /app

# Copy package files first (for caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Expose port for dev server
EXPOSE 5173

# Start dev server
CMD ["npm", "run", "dev"]
